<h1>Produto</h1>

<a href="/admin/produto/create" class="btn btn-primary">Novo Produto</a>

<table class="table">
    <thead>
        <tr>
            <th>
                id
            </th>
            <th>
                Nome
            </th>
            <th>
                Preço
            </th>
            <th>
                Especificação
            </th>
            <th>
                Lucro
            </th>
            <th>
                Foto
            </th>
            <th>
                Categoria
            </th>
            <th>
                Editar
            </th>
            <th>
                Remover
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($produtos as $produto) { ?>
            <tr>
                <td>
                    <?= $produto->id ?>
                </td>
                <td>
                    <?= $produto->nome ?>
                </td>
                <td>
                    <?= $produto->preco ?>
                </td>
                <td>
                    <?= $produto->especificacao ?>
                </td>
                <td>
                    <?= $produto-> lucro?>
                </td>
                <td width="10%" height="10%">
                    <img width="70%" height="70%" src="/img/fotos_produtos/<?= $produto->foto ?>"></img>
                </td>
                <td>
                    <?php foreach ($produto->categorias as $categoria) {

                    } ?>
                </td>
                <td>
                    <a href="/admin/produto/update/id/<?= $produto->id; ?>"><i class="glyphicon glyphicon-edit"></i></a>
                </td>
                <td>
                    <a href="/admin/produto/delete/id/<?= $produto->id; ?>"><i class="glyphicon glyphicon-trash"></i></a>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>
